// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: commands.proto
#ifndef GRPC_commands_2eproto__INCLUDED
#define GRPC_commands_2eproto__INCLUDED

#include "commands.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace grpcdemo {

class CommandService final {
 public:
  static constexpr char const* service_full_name() {
    return "grpcdemo.CommandService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status ExecuteCommand(::grpc::ClientContext* context, const ::grpcdemo::CommandRequest& request, ::grpcdemo::CommandResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::grpcdemo::CommandResponse>> AsyncExecuteCommand(::grpc::ClientContext* context, const ::grpcdemo::CommandRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::grpcdemo::CommandResponse>>(AsyncExecuteCommandRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::grpcdemo::CommandResponse>> PrepareAsyncExecuteCommand(::grpc::ClientContext* context, const ::grpcdemo::CommandRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::grpcdemo::CommandResponse>>(PrepareAsyncExecuteCommandRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void ExecuteCommand(::grpc::ClientContext* context, const ::grpcdemo::CommandRequest* request, ::grpcdemo::CommandResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ExecuteCommand(::grpc::ClientContext* context, const ::grpcdemo::CommandRequest* request, ::grpcdemo::CommandResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::grpcdemo::CommandResponse>* AsyncExecuteCommandRaw(::grpc::ClientContext* context, const ::grpcdemo::CommandRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::grpcdemo::CommandResponse>* PrepareAsyncExecuteCommandRaw(::grpc::ClientContext* context, const ::grpcdemo::CommandRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status ExecuteCommand(::grpc::ClientContext* context, const ::grpcdemo::CommandRequest& request, ::grpcdemo::CommandResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::grpcdemo::CommandResponse>> AsyncExecuteCommand(::grpc::ClientContext* context, const ::grpcdemo::CommandRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::grpcdemo::CommandResponse>>(AsyncExecuteCommandRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::grpcdemo::CommandResponse>> PrepareAsyncExecuteCommand(::grpc::ClientContext* context, const ::grpcdemo::CommandRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::grpcdemo::CommandResponse>>(PrepareAsyncExecuteCommandRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void ExecuteCommand(::grpc::ClientContext* context, const ::grpcdemo::CommandRequest* request, ::grpcdemo::CommandResponse* response, std::function<void(::grpc::Status)>) override;
      void ExecuteCommand(::grpc::ClientContext* context, const ::grpcdemo::CommandRequest* request, ::grpcdemo::CommandResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::grpcdemo::CommandResponse>* AsyncExecuteCommandRaw(::grpc::ClientContext* context, const ::grpcdemo::CommandRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::grpcdemo::CommandResponse>* PrepareAsyncExecuteCommandRaw(::grpc::ClientContext* context, const ::grpcdemo::CommandRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_ExecuteCommand_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status ExecuteCommand(::grpc::ServerContext* context, const ::grpcdemo::CommandRequest* request, ::grpcdemo::CommandResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_ExecuteCommand : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ExecuteCommand() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ExecuteCommand() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExecuteCommand(::grpc::ServerContext* /*context*/, const ::grpcdemo::CommandRequest* /*request*/, ::grpcdemo::CommandResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestExecuteCommand(::grpc::ServerContext* context, ::grpcdemo::CommandRequest* request, ::grpc::ServerAsyncResponseWriter< ::grpcdemo::CommandResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ExecuteCommand<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_ExecuteCommand : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ExecuteCommand() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpcdemo::CommandRequest, ::grpcdemo::CommandResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpcdemo::CommandRequest* request, ::grpcdemo::CommandResponse* response) { return this->ExecuteCommand(context, request, response); }));}
    void SetMessageAllocatorFor_ExecuteCommand(
        ::grpc::MessageAllocator< ::grpcdemo::CommandRequest, ::grpcdemo::CommandResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::grpcdemo::CommandRequest, ::grpcdemo::CommandResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ExecuteCommand() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExecuteCommand(::grpc::ServerContext* /*context*/, const ::grpcdemo::CommandRequest* /*request*/, ::grpcdemo::CommandResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ExecuteCommand(
      ::grpc::CallbackServerContext* /*context*/, const ::grpcdemo::CommandRequest* /*request*/, ::grpcdemo::CommandResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_ExecuteCommand<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_ExecuteCommand : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ExecuteCommand() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ExecuteCommand() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExecuteCommand(::grpc::ServerContext* /*context*/, const ::grpcdemo::CommandRequest* /*request*/, ::grpcdemo::CommandResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_ExecuteCommand : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ExecuteCommand() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_ExecuteCommand() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExecuteCommand(::grpc::ServerContext* /*context*/, const ::grpcdemo::CommandRequest* /*request*/, ::grpcdemo::CommandResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestExecuteCommand(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ExecuteCommand : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ExecuteCommand() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ExecuteCommand(context, request, response); }));
    }
    ~WithRawCallbackMethod_ExecuteCommand() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExecuteCommand(::grpc::ServerContext* /*context*/, const ::grpcdemo::CommandRequest* /*request*/, ::grpcdemo::CommandResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ExecuteCommand(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ExecuteCommand : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ExecuteCommand() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::grpcdemo::CommandRequest, ::grpcdemo::CommandResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::grpcdemo::CommandRequest, ::grpcdemo::CommandResponse>* streamer) {
                       return this->StreamedExecuteCommand(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ExecuteCommand() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ExecuteCommand(::grpc::ServerContext* /*context*/, const ::grpcdemo::CommandRequest* /*request*/, ::grpcdemo::CommandResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedExecuteCommand(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::grpcdemo::CommandRequest,::grpcdemo::CommandResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_ExecuteCommand<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_ExecuteCommand<Service > StreamedService;
};

}  // namespace grpcdemo


#endif  // GRPC_commands_2eproto__INCLUDED
