// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: commands.proto

#include "commands.pb.h"
#include "commands.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace grpcdemo {

static const char* CommandService_method_names[] = {
  "/grpcdemo.CommandService/ExecuteCommand",
};

std::unique_ptr< CommandService::Stub> CommandService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< CommandService::Stub> stub(new CommandService::Stub(channel, options));
  return stub;
}

CommandService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_ExecuteCommand_(CommandService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status CommandService::Stub::ExecuteCommand(::grpc::ClientContext* context, const ::grpcdemo::CommandRequest& request, ::grpcdemo::CommandResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::grpcdemo::CommandRequest, ::grpcdemo::CommandResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ExecuteCommand_, context, request, response);
}

void CommandService::Stub::async::ExecuteCommand(::grpc::ClientContext* context, const ::grpcdemo::CommandRequest* request, ::grpcdemo::CommandResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::grpcdemo::CommandRequest, ::grpcdemo::CommandResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ExecuteCommand_, context, request, response, std::move(f));
}

void CommandService::Stub::async::ExecuteCommand(::grpc::ClientContext* context, const ::grpcdemo::CommandRequest* request, ::grpcdemo::CommandResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ExecuteCommand_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::grpcdemo::CommandResponse>* CommandService::Stub::PrepareAsyncExecuteCommandRaw(::grpc::ClientContext* context, const ::grpcdemo::CommandRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::grpcdemo::CommandResponse, ::grpcdemo::CommandRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ExecuteCommand_, context, request);
}

::grpc::ClientAsyncResponseReader< ::grpcdemo::CommandResponse>* CommandService::Stub::AsyncExecuteCommandRaw(::grpc::ClientContext* context, const ::grpcdemo::CommandRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncExecuteCommandRaw(context, request, cq);
  result->StartCall();
  return result;
}

CommandService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CommandService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CommandService::Service, ::grpcdemo::CommandRequest, ::grpcdemo::CommandResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CommandService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::grpcdemo::CommandRequest* req,
             ::grpcdemo::CommandResponse* resp) {
               return service->ExecuteCommand(ctx, req, resp);
             }, this)));
}

CommandService::Service::~Service() {
}

::grpc::Status CommandService::Service::ExecuteCommand(::grpc::ServerContext* context, const ::grpcdemo::CommandRequest* request, ::grpcdemo::CommandResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace grpcdemo

